### ISSUE TITLE
Feature request: Option to only show ROS node processes

### ISSUE THREAD

**Issue by SammyRamone** [iwatake2222/rotop#2]
First, thanks a lot for programming this helpful tool. I was looking for a small tool like this since some time, as it is very annoying to find out how much CPU load one node generates.
I think it would be great if there was an option like "--only-ros" which then only shows processes belonging to ROS nodes (and no other processes that are running, e.g. Firefox). I guess most people are actually just interested in these node processes and the long list of other processes makes the GUI less clear.

**Comment by iwatake2222** [comment]
Thank you for telling your idea. It sounds nice!
It might be difficult to judge whether a process is ROS node process or not, there should be a solution.

**Comment by SammyRamone** [comment]
I think you already check what type of process it is here https://github.com/iwatake2222/rotop/blob/af3ea3dbaa70ed394da1c4270a3bda8c344e3d3a/src/rotop/top_runner.py#L210-L222
So maybe you could use that as a basis.

**Comment by iwatake2222** [comment]
@SammyRamone 
Hey, I released the new version to support this feature 🚀 
` pip3 install rotop==v1.0.1`

**Comment by SammyRamone** [comment]
Works perfectly, thanks for implementing 😃
