### ISSUE TITLE
High CPU load using GUI

### ISSUE THREAD

**Issue by SammyRamone** [iwatake2222/rotop#3]
Running rotop without GUI is fine, however if I use the GUI, I get around 500% CPU load. Looks a bit like a busy waiting problem.
My system:
Ubuntu 22.04 running in WSL2
Python 3.10
rotop 1.0.0

**Comment by iwatake2222** [comment]
@SammyRamone 
The new version with a workaround is released. Please see if it works in you PC.
In my PC, CPU usage decreased from 200 % to 5% in WSL. However, in AWS EC2, it decreased from 1000% only to 50%.

`pip3 install rotop==1.0.2`

**Comment by SammyRamone** [comment]
It is much better now. I get around 30% CPU load in my WSL, which is fine for me.
Thanks for fixing it 🙂
